
module.exports = Object.freeze({
    MODAL_BODY_TYPES : {
        USER_DETAIL : "USER_DETAIL",
        LEAD_ADD_NEW : "LEAD_ADD_NEW",
        CONFIRMATION : "CONFIRMATION",
        DEFAULT : "",
        MANAGER_ADD_NEW:"MANAGER_ADD_NEW",
        EXECUTIVE_ADD_NEW:"EXECUTIVE_ADD_NEW",
    },

    RIGHT_DRAWER_TYPES : {
        NOTIFICATION : "NOTIFICATION",
        CALENDAR_EVENTS : "CALENDAR_EVENTS",
    },

    CONFIRMATION_MODAL_CLOSE_TYPES : {
        LEAD_DELETE : "LEAD_DELETE",
        MANAGER_DELETE : "MANAGER_DELETE",
        EXECUTIVE_DELETE : "EXECUTIVE_DELETE",
    },
});
